---
- hosts: all
  remote_user: root

  tasks:
    #################################################################
    # Certificate Authority - Host
    #################################################################
  - name: download ca host public key
    ansible.builtin.uri:
      url: http://{{ ca_host }}/crypto/public
      return_content: true
    register: ca_host_pub_key
    run_once: True

  - name: add ca host public key to known_hosts
    ansible.builtin.known_hosts:
      path: /root/.ssh/known_hosts
      name: ca_host
      key: "ca_host {{ ca_host_pub_key.content }}"
    delegate_to: localhost
    run_once: True

    #################################################################
    # Issue Host Ticket
    #################################################################
  - name: issue host ticket
    ansible.builtin.shell: |
      ssh -tt {{ ansible_facts['fqdn'] }}@ca_host
    delegate_to: localhost
    register: ticket

  - name: create host ticket file
    copy:
      dest: "/root/.ssh_ticket"
      content: "{{ ticket.stdout }}"
      mode: '0600'